-- local project_root = "/Volumes/Sandisk/Projects/Help/NodeJs/lsp-from-scratch"
-- local server_path = project_root .. "/server/src/server.ts"
-- local ts_node = project_root .. "/node_modules/.bin/ts-node"
--
-- local capabilities = vim.lsp.protocol.make_client_capabilities()
--
-- vim.lsp.start({
--     name = "lsp_from_scratch",
--     cmd = {
--         "npx",
--         ts_node,
--         server_path,
--     },
--     root_dir = project_root,
--     capabilities = capabilities,
-- })
